server:
  port: 8081
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: book-service
              uri: http://localhost:8080
              predicates:
                - Path=/api/books/**
              filters:
                - AddRequestHeader=X-Request-Source, API-Gateway-Request